language: csharp
mono: none
dotnet: 3.1
solution: HelloTravis.sln
script:
- dotnet restore
- dotnet build
- dotnet test HelloTravis_test/HelloTravis_test.csproj
before_deploy:
- ls
deploy:
  provider: releases
  skip_cleanup: true
  on:
    branch: develop
  token:
    secure: eEiSHBCOH5TazmZGoOiIYJSWoYlbs1CKdBm3votVlBK3fm5HePssukcUn2XE2O8gG5Ms/54HXIyD9Vpxj5C+bMTNvu5uMAQJF6OsjJluzQR7gMhIhHISBYS+e8GTR5VnFoH1yg8Y+hhr6n0M8ZA7nMK0dsPHngxMQlu7kV2lp5xqNomMZUF3IJa0Ew2jK5tiIeN3HMB3RwfuEygpAApeW6LA0dZFC7lT6t4dsomkoFTke+UgXslUa3QmAj805LFoW0gOky+zl9XnQU1wfELWJuXarY5aPDWg0SxpkLl17FsI3OaagBMMve13CAhvQTaVWtmOns2XWcdsAHfgOyzsS998/v57YuyEH32OPTb8H33QUWiZWWTjCHvEH+/kvHS+1zfyPs4acmdYMn6b3wTAaMYvuVeawPDZ4+KOCV9IZoyEFL3bOJ47bG7qTSGVxIGtJa+V2pXLAtTvChE0qhcDWKp41BH30KYGOOowPggeCBS4W/NMUR3w76095ZzaA6jRopW6ddi33glskFzNFL2jwTIyCjc5lk2WXfFZS0Id/iv4E6J4gjapJLE5FubaHjHDmttienVai1FRcHFZfqjVL3S4a2Z98AGGi8Y7MMB4RKz6VmiHwI19cvEIMckSaDqdceu5SUH/3+mfkKU4ozEY6mJ5GBgnk2nSx2QpyZB+2wo=
